#production settings
eureka:
  client:
    region: potsdamerplatz
    availabilityZones:
      potsdamerplatz: one
    registerWithEureka: true
    fetchRegistry: true
    preferSameZoneEureka: true
    serviceUrl:
      one: http://localhost:8761/serviceregistry/eureka/
    healthcheck:
      enabled: true
