#!/bin/sh

set -e

update-rc.d -f [[artifactId]] remove

if [ -f '/etc/authbind/byport/80' ]
then
  rm /etc/authbind/byport/80
fi

if [ -f '/etc/authbind/byport/80' ]
then
  rm /etc/authbind/byport/443
fi
