#!/bin/sh

set -e

if which initctl >/dev/null && initctl version | grep -q upstart; then
    # Using upstart
    initctl stop [[artifactId]] || true
else
    # Using SysV init scripts
    service [[artifactId]] stop || true
fi